#platform :ios, '15.0'
platform :ios, '15.4'
target 'iosApp' do
  use_frameworks!

  # Dependencias de Firebase
      pod 'Firebase'
      pod 'Firebase/Storage'
      pod 'Firebase/Auth'
      pod 'Firebase/Firestore'
      pod 'Firebase/Database'
      pod 'Firebase/Messaging'
      pod 'MapLibre', '6.9.0'
      pod 'GoogleSignIn'
      pod 'composeApp', :path => '../composeApp'

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Forzamos deployment target iOS 15.4 (o 12.0)
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.4'
      end
    end
  end
end
